In [1]:
from random import randint, choice, random
import proto
import familia as fml

In [2]:
proto_alfa = proto.ProtoLingua(0)

# configução da lingua inicial
primeiros_dialetos:int = 1
print(f'Primeiros dialetos: {primeiros_dialetos}')
dialetos = fml.FamiliaLinguistica(
    primeiros_dialetos,
    proto_alfa.proto_lingua,
    proto_alfa.proto_lingua['lingua'][randint(0,len(proto_alfa.proto_lingua['lingua'].keys())-1)]['palavra'],
    0
)

Primeiros dialetos: 1

c:\Users\caraf\OneDrive\Área de Trabalho\projetos_proprios\Python\projeto_simulador_linguistico\tools.py:1077: FutureWarning: Possible nested set at position 2
  word = re.sub(f[0], f[1], word)

In [3]:
dialetos.desenvolver_filhas(5)

Quantidade de dialetos: 1
original ['a', 'i', 'u', 'e', 'o']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
ej ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ']
ej ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
Quantidade de dialetos: 1
original ['a', 'i', 'u', 'e', 'o']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
ej ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ']
ej ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
Quantidade de dialetos: 1
original ['a', 'i', 'u', 'e', 'o']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
ej ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ']
ej ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
Quantidade de dialetos: 1
original ['a', 'i', 'u', 'e', 'o']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
ej ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ']
ej ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
Quantidade de dialetos: 1
original ['a', 'i', 'u', 'e', 'o']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
ej ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ej ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']

In [4]:
dialetos.ver_gramatica(topico = "todos")

==================== Língua original ====================
==================== us ej ====================
:::::::::: afixos
||            cargo  :::  uk
||            locativo  :::  oje
||            dativo  :::  aɾe
||            acusativo  :::  ɾejɐ
||            instrumental  :::  esɐ
||            genitivo  :::  ne
||
:::::::::: pronomes
||            eu  :::  ki
||            voce  :::  esɐɾ
||            aquele_h  :::  ɾejɐok
||            aquele_m  :::  ɾejɐtaj
||            nos_inclusivo  :::  esɐɾki
||            nos_exclusivo  :::  ɾejɐokki
||

In [5]:
dialetos.mostrar_('s')

Língua original
==================================================
significado: evocar
	| gramatica: verbo
	| palavra: /at/
	| outros significados:
	| Usabilidade: 1.00
==================================================

Língua ej
==================================================
| significado: evocar
	| gramatica: verbo
	| palavra: /'at./
	| posicao: preposicao
	Casos gramaticais:
		| cargo: /ukɐt/
		| locativo: /ojeɐt/
		| dativo: /ɐɾeɐt/
		| acusativo: /ɾejaːt/
		| instrumental: /esaːt/
		| genitivo: /neɐt/
	| outros significados:
	| Usabilidade: 1.00
==================================================

In [6]:
gen_sigs = []
ramos = [dialetos]
for r in ramos:
    sigs = []
    for s in r.retornar_nome_lingua()[1]:
        if(s not in gen_sigs):
            sigs.extend(s)
    gen_sigs.extend(sigs)
gen_sigs

Mae nao encontrada?

['morrer']

In [7]:
palavras = dialetos.sortear_palavras(10)
# palavras = ["saber"] # se quiser ver uma palavra específica
# palavras = gen_sigs
for p in palavras:
    # print("Ramo:", r.nome_lingua_mae)
    for r in ramos:
        r.mostrar_palavra_todas_linguas(p, False, True)
        print("")
print("="*50)

 dividir original   ej
     127     woje woje

 som original ej
  47       up op

 juntar original ej
    129       ɾe ɾe

 alto original ej
  166       ni ne

 alem original  ej
   66      upo opo

 todo original  ej
  208      owʊ owʊ

 furia original ej
    81       ji ji

 cauda original  ej
    27      ite ete

 mostrar original ej
     122       mu mɔ

 semente original ej
      54       op op

==================================================

In [8]:
# dialetos._ver_variacoes_de_palavra_(1)

dialetos._ver_inteligibilidade_()
# se quiser fazer com que alguma lingua se torne imutavel, descomente as linhas abaixo
#lingua_imutavel = ""
# remover = [lingua_imutavel]
# for r in remover:
    # dialetos.nao_mutaveis(r)

Intelegibilidade entre original e ej: 1.7951998050682285

In [ ]:
nome_lingua = 'ej'
ramo_a = fml.FamiliaLinguistica(randint(0,10), dialetos.dialetos_criados[nome_lingua], nome_lingua, geracao = 1)
# try some exemples below
# ramo_a1 = fml.FamiliaLinguistica(randint(0,10), ramo_a.dialetos_criados["ʉk"], "ʉk", geracao = 2)
# ramo_a2 = fml.FamiliaLinguistica(randint(0,10), ramo_a.dialetos_criados['ʊnʊnwa'], 'ʊnʊnwa', geracao = 2)

In [10]:
ramos:list[fml.FamiliaLinguistica] = [ramo_a] # you can add your vars here

In [ ]:
iter:int =  5 # valor pequeno para que soem proximos a sotaques/dialetos
for r in ramos:
    r.desenvolver_filhas(iter)

Quantidade de dialetos: 5
original ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
ɾe ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ɾe ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
nowɔ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
nowɔ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
tæmʊ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ', 'ʉ']
tæmʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
os ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
os ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
ewejme ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ewejme ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
Quantidade de dialetos: 5
original ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
ɾe ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ɾe ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
nowɔ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
nowɔ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
tæmʊ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ', 'ʉ']
tæmʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
os ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
os ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
ewejme ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ewejme ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
Quantidade de dialetos: 5
original ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
ɾe ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ɾe ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
nowɔ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
nowɔ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ʦ']
tæmʊ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ', 'ʉ', 'ɤ']
tæmʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
os ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
os ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'b']
ewejme ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ewejme ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
Quantidade de dialetos: 5
original ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
ɾe ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ɾe ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'b']
nowɔ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
nowɔ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ʦ']
tæmʊ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ', 'ʉ', 'ɤ']
tæmʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
os ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
os ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'b']
ewejme ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
ewejme ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
Quantidade de dialetos: 5
original ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
ɾe ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ', 'ɛ']
ɾe ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'b', 'ʦ']
nowɔ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
nowɔ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ʦ']
tæmʊ ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ', 'ʉ', 'ɤ']
tæmʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's']
os ['a', 'i', 'u', 'e', 'o', 'æ', 'ɔ', 'ʌ', 'ɵ']
os ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'b', 'ʦ']
ewejme ['a', 'i', 'u', 'e', 'o', 'æ', 'ʌ', 'ɵ']
ewejme ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'b']

In [12]:
display(dialetos.mostrar_tabela()) 
display(ramo_a.mostrar_tabela())
# display(ramo_a1.mostrar_tabela())
# display(ramo_a2.mostrar_tabela())

            original                   ej
0      isɐɾ (pessoa)        esɐɾ (pessoa)
1         uk (homem)           ok (homem)
2       taj (mulher)         taj (mulher)
3    wu (semelhante)      wɔ (semelhante)
4       naje (bicho)         næje (bicho)
..               ...                  ...
223                   ewijet (recipiente)
224                      wɔæpe (vermelho)
225                        menɐɔwʊ (vila)
226                    tujpɪ (mudar_gelo)
227                         ejaɾe (matar)

[228 rows x 2 columns]

,original,ɾe,nowɔ,tæmʊ,os,ewejme
0,esɐɾ (pessoa),esɐɾ (pessoa),esɐɾ (pessoa),esɐɾ (pessoa),esɐɾ (pessoa),esɐɾ (pessoa)
1,ok (homem),ɞk (homem),ok (homem),ok (homem),ok (homem),ɞk (homem)
2,taj (mulher),taj (mulher),taj (mulher),tæj (mulher),tæj (mulher),taj (mulher)
3,wɔ (semelhante),wʌ (semelhante),wo (semelhante),wɔ (semelhante),wʌ (semelhante),wɔ (semelhante)
4,næje (bicho),næje (bicho),næje (bicho),naje (bicho),næje (bicho),naje (bicho)
...,...,...,...,...,...,...
228,,emtʊj (granizo),nemenɐ (alto_terra),tʉjem (granizo),mewo (membro_topo),wojewoje (fracao)
229,,enpɪ (mudar_coracao),nɔjwɔje (contar),tujem (granizo),ʊsenbem (umidade),newet (cha)
230,,peʦɛ (corpo_chao),empɔt (tipo-minerio),esɪɾewuwɔ (mar),esɪɾewuwɐ (agua),woæno (azul)
231,,ɐɾeːjɐ (criar),ɐmɛjme (ferida),ɐnoɔkhahɐ (divindade-agua),nɐjeʦɔw (tipo-animal),paet (recipiente)
232,,wɔjɾo (tipo-arvore),sɐwape (congelado),ɾejet (alcool),ɔmɐumɔ (ferida),nojwɔje (contar)

In [13]:
ramo_a.ver_gramatica('todos')

==================== Língua original ====================
:::::::::: afixos
||            cargo  :::  uk
||            locativo  :::  oje
||            dativo  :::  aɾe
||            acusativo  :::  ɾejɐ
||            instrumental  :::  esɐ
||            genitivo  :::  ne
||
:::::::::: pronomes
||            eu  :::  ki
||            voce  :::  esɐɾ
||            aquele_h  :::  ɾejɐok
||            aquele_m  :::  ɾejɐtaj
||            nos_inclusivo  :::  esɐɾki
||            nos_exclusivo  :::  ɾejɐokki
||
==================== us ɾe ====================
:::::::::: afixos
||            cargo  :::  uk
||            locativo  :::  oje
||            dativo  :::  aɾe
||            acusativo  :::  ɾejɐ
||            instrumental  :::  esɐ
||            genitivo  :::  ne
||
:::::::::: pronomes
||            eu  :::  ki
||            voce  :::  esɐɾ
||            aquele_h  :::  ɾejaok
||            aquele_m  :::  ɾejatɐj
||            nos_inclusivo  :::  esaɾkɪ
||            nos_exclusivo  :::  ɾɪjaokː
||
==================== us nowɔ ====================
:::::::::: afixos
||            cargo  :::  uk
||            locativo  :::  oje
||            dativo  :::  aɾe
||            acusativo  :::  ɾijɐ
||            instrumental  :::  isɐ
||            genitivo  :::  ne
||
:::::::::: pronomes
||            eu  :::  ki
||            voce  :::  esɐɾ
||            aquele_h  :::  ɾejaog
||            aquele_m  :::  ɾejatɐj
||            nos_inclusivo  :::  esaɾk
||            nos_exclusivo  :::  ɾejaokː
||
==================== us tæmʊ ====================
:::::::::: afixos
||            cargo  :::  uk
||            locativo  :::  oje
||            dativo  :::  aɾe
||            acusativo  :::  ɾejɐ
||            instrumental  :::  is
||            genitivo  :::  ne
||
:::::::::: pronomes
||            eu  :::  ki
||            voce  :::  esɐɾ
||            aquele_h  :::  ɾɪjaog
||            aquele_m  :::  ɾejatɐj
||            nos_inclusivo  :::  esaɾkɪ
||            nos_exclusivo  :::  ɾejkːɪ
||
==================== us os ====================
:::::::::: afixos
||            cargo  :::  ug
||            locativo  :::  oje
||            dativo  :::  aɾe
||            acusativo  :::  ɾejɐ
||            instrumental  :::  is
||            genitivo  :::  ne
||
:::::::::: pronomes
||            eu  :::  ki
||            voce  :::  esɐɾ
||            aquele_h  :::  ɾɪjaok
||            aquele_m  :::  ɾejatɐj
||            nos_inclusivo  :::  esaɾkɪ
||            nos_exclusivo  :::  ɾejkː
||
==================== us ewejme ====================
:::::::::: afixos
||            cargo  :::  uk
||            locativo  :::  oje
||            dativo  :::  aɾe
||            acusativo  :::  ɾej
||            instrumental  :::  isɐ
||            genitivo  :::  ni
||
:::::::::: pronomes
||            eu  :::  ki
||            voce  :::  esɐɾ
||            aquele_h  :::  ɾejaok
||            aquele_m  :::  ɾɪjatɐj
||            nos_inclusivo  :::  esaɾk
||            nos_exclusivo  :::  ɾejkːɪ
||