In [1]:
from random import randint, choice, random
from proto import ProtoLingua
from familia import FamiliaLinguistica as Familia

In [2]:
proto_alfa = ProtoLingua(0)

# configução da lingua inicial
primeiros_dialetos:int = 1
print(f'Primeiros dialetos: {primeiros_dialetos}')
dialetos = Familia(
    primeiros_dialetos,
    proto_alfa.proto_lingua,
    proto_alfa.proto_lingua['lingua'][randint(0,len(proto_alfa.proto_lingua['lingua'].keys())-1)]['palavra'],
    0
)

Primeiros dialetos: 1

In [3]:
dialetos.desenvolver_filhas(5)

Quantidade de dialetos: 1
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
uɾɪ ['a', 'i', 'u']
uɾɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
Quantidade de dialetos: 1
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
uɾɪ ['a', 'i', 'u']
uɾɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
Quantidade de dialetos: 1
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
uɾɪ ['a', 'i', 'u']
uɾɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
Quantidade de dialetos: 1
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
uɾɪ ['a', 'i', 'u']
uɾɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
Quantidade de dialetos: 1
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
uɾɪ ['a', 'i', 'u']
uɾɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']

In [4]:
dialetos.ver_gramatica(topico = "todos")

==================== Língua original ====================
==================== ikʊ uɾɪ ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ap
||            instrumental  :::  ta
||            genitivo  :::  mij
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾɪ
||            nos_inclusivo  :::  aɾna
||            nos_exclusivo  :::  aɾuɾɪ
||

In [5]:
dialetos.mostrar_('s')

Língua original
==================================================
significado: cabeca
	| gramatica: substantivo
	| palavra: /aj/
	| outros significados:
	| Usabilidade: 1.00
==================================================

Língua uɾɪ
==================================================
| significado: cabeca
	| gramatica: substantivo
	| palavra: /'aj./
	| posicao: preposicao
	Casos gramaticais:
		| cargo: /ɐtipɐj/
		| locativo: /ɐmawɐj/
		| dativo: /miɐj/
		| acusativo: /apɐj/
		| instrumental: /taːj/
		| genitivo: /mijɐj/
	| outros significados:
	| Usabilidade: 1.00
==================================================
| significado: cabeca
	| gramatica: substantivo
	| palavra: /'suɾ.jʊm./
	| posicao: preposicao
	Casos gramaticais:
		| cargo: /ɐtɪpsuɾjʊm/
		| locativo: /ɐmɐwsuɾjʊm/
		| dativo: /mɪsuɾjʊm/
		| acusativo: /ɐpsuɾjʊm/
		| instrumental: /tɐsuɾjʊm/
		| genitivo: /mɪjsuɾjʊm/
	| outros significados:
	| Usabilidade: 1.00
==================================================

In [6]:
gen_sigs = []
ramos = [dialetos]
for r in ramos:
    sigs = []
    for s in r.retornar_nome_lingua()[1]:
        if(s not in gen_sigs):
            sigs.extend(s)
    gen_sigs.extend(sigs)
gen_sigs

Mae nao encontrada?

['osso']

In [7]:
palavras = dialetos.sortear_palavras(10)
# palavras = ["saber"] # se quiser ver uma palavra específica
# palavras = gen_sigs
for p in palavras:
    # print("Ramo:", r.nome_lingua_mae)
    for r in ramos:
        r.mostrar_palavra_todas_linguas(p, False, True)
        print("")
print("="*50)

 verdadeiro original uɾɪ
        191      ujɐ ujɐ

 empurrar original  uɾɪ
      143     apʊɾ apʊɾ

 queimar original  uɾɪ
     154     paɾʊ paɾʊ

 ramo original  uɾɪ
   55     anɪj anjɪ

 correr original uɾɪ
     97      iɾɪ iɾɪ

 esposo original  uɾɪ
     87     utɐɾ utɐɾ

 mover original uɾɪ
   104      tap tap

 pensar original uɾɪ
    116      imʊ imʊ

 chuva original   uɾɪ
    43      tis   tis
   223      --- ɪkisɪ

 chao original uɾɪ
   60       uk  uk

==================================================

In [8]:
# dialetos._ver_variacoes_de_palavra_(1)

dialetos._ver_inteligibilidade_()
# se quiser fazer com que alguma lingua se torne imutavel, descomente as linhas abaixo
#lingua_imutavel = ""
# remover = [lingua_imutavel]
# for r in remover:
    # dialetos.nao_mutaveis(r)

Intelegibilidade entre original e uɾɪ: 1.8377192982456148

In [9]:
nome_lingua = 'uɾɪ'
ramo_a = Familia(randint(0,10), dialetos.dialetos_criados[nome_lingua], nome_lingua, geracao = 1)
# try some exemples below
# ramo_a1 = fml.FamiliaLinguistica(randint(0,10), ramo_a.dialetos_criados["ʉk"], "ʉk", geracao = 2)
# ramo_a2 = fml.FamiliaLinguistica(randint(0,10), ramo_a.dialetos_criados['ʊnʊnwa'], 'ʊnʊnwa', geracao = 2)

In [10]:
ramos:list[Familia] = [ramo_a] # you can add your vars here

In [11]:
iter:int =  5 # valor pequeno para que soem proximos a sotaques/dialetos
for r in ramos:
    r.desenvolver_filhas(iter)

Quantidade de dialetos: 8
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
tuwɪ ['a', 'i', 'u']
tuwɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
tap ['a', 'i', 'u', 'ä']
tap ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
ja ['a', 'i', 'u']
ja ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'β']
imɐw ['a', 'i', 'u']
imɐw ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
uɾjʊ ['a', 'i', 'u']
uɾjʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
utɐm ['a', 'i', 'u']
utɐm ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
an ['a', 'i', 'u']
an ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'h']
nuj ['a', 'i', 'u']
nuj ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
Quantidade de dialetos: 8
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
tuwɪ ['a', 'i', 'u']
tuwɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
tap ['a', 'i', 'u', 'ä']
tap ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
ja ['a', 'i', 'u']
ja ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'β']
imɐw ['a', 'i', 'u']
imɐw ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'b']
uɾjʊ ['a', 'i', 'u']
uɾjʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
utɐm ['a', 'i', 'u']
utɐm ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'β', 'ɺ']
an ['a', 'i', 'u']
an ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'h']
nuj ['a', 'i', 'u', 'ä']
nuj ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
Quantidade de dialetos: 8
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
tuwɪ ['a', 'i', 'u']
tuwɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'ʦ']
tap ['a', 'i', 'u', 'ä']
tap ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'ʦ']
ja ['a', 'i', 'u']
ja ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'β']
imɐw ['a', 'i', 'u']
imɐw ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'b']
uɾjʊ ['a', 'i', 'u']
uɾjʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
utɐm ['a', 'i', 'u']
utɐm ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'β', 'ɺ']
an ['a', 'i', 'u']
an ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'h', 'θ']
nuj ['a', 'i', 'u', 'ä']
nuj ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
Quantidade de dialetos: 8
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
tuwɪ ['a', 'i', 'u']
tuwɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'ʦ']
tap ['a', 'i', 'u', 'ä']
tap ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'ʦ']
ja ['a', 'i', 'u']
ja ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'β', 'h']
imɐw ['a', 'i', 'u', 'ä']
imɐw ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'b']
uɾjʊ ['a', 'i', 'u']
uɾjʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'ʝ']
utɐm ['a', 'i', 'u', 'æ']
utɐm ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'β', 'ɺ', 'l']
an ['a', 'i', 'u', 'e']
an ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'h', 'θ']
nuj ['a', 'i', 'u', 'ä', 'y']
nuj ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'b']
Quantidade de dialetos: 8
original ['a', 'i', 'u']
original ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ']
tuwɪ ['a', 'i', 'u']
tuwɪ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'ʦ']
tap ['a', 'i', 'u', 'ä']
tap ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'ʦ']
ja ['a', 'i', 'u']
ja ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'h']
imɐw ['a', 'i', 'u', 'ä', 'o']
imɐw ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'b']
uɾjʊ ['a', 'i', 'u']
uɾjʊ ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'ʝ']
utɐm ['a', 'i', 'u', 'æ']
utɐm ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'β', 'ɺ', 'l']
an ['a', 'i', 'u', 'e']
an ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'h', 'θ']
nuj ['a', 'i', 'u', 'ä', 'y']
nuj ['p', 't', 'k', 'w', 'j', 'm', 'n', 's', 'ɾ', 'b']

In [12]:
display(dialetos.mostrar_tabela()) 
display(ramo_a.mostrar_tabela())
# display(ramo_a1.mostrar_tabela())
# display(ramo_a2.mostrar_tabela())

              original                     uɾɪ
0          na (pessoa)             na (pessoa)
1           aɾ (homem)              aɾ (homem)
2          is (mulher)             is (mulher)
3    kapɪ (semelhante)       kapɪ (semelhante)
4          uɾɐ (bicho)             uɾɐ (bicho)
..                 ...                     ...
223                              ɪkisɪ (chuva)
224                          ɪkjakʊ (tormenta)
225                     kɐɾwikɪp (tipo-arvore)
226                              ʊnawɾʊw (dez)
227                            ʊɾajɐ (rebanho)

[228 rows x 2 columns]

,original,tuwɪ,tap,ja,imɐw,uɾjʊ,utɐm,an,nuj
0,na (pessoa),na (pessoa),nä (pessoa),na (pessoa),na (pessoa),na (pessoa),na (pessoa),na (pessoa),na (pessoa)
1,aɾ (homem),aɾ (homem),aɾ (homem),aɾ (homem),äɾ (homem),aɾ (homem),aɺ (homem),aɾ (homem),aɾ (homem)
2,is (mulher),is (mulher),is (mulher),is (mulher),is (mulher),is (mulher),is (mulher),ih (mulher),ys (mulher)
3,kapɪ (semelhante),kapɪ (semelhante),kapɪ (semelhante),kapɪ (semelhante),kabɪ (semelhante),kapɪ (semelhante),kapɪ (semelhante),kapɪ (semelhante),kapɪ (semelhante)
4,uɾɐ (bicho),uɾɐ (bicho),uɾɐ (bicho),uɾɐ (bicho),uɾɐ (bicho),uɾɐ (bicho),uɾɐ (bicho),uɾɐ (bicho),uɾɐ (bicho)
...,...,...,...,...,...,...,...,...,...
228,,jɐjʦiɐɾ (reuniao),ɪʦikɪ (inflamacao),ɪswukʊ (granizo),sʊjikʊ (alto_terra),ɐtɪpuɾɐ (criatura-mitologia),patpɐt (fracao),ʊɾajɐ (rebanho),ɐwjanʊj (cha)
229,,ɐkʊpukʊ (lama),kɐpjakʊ (azul),kɐɾapɪ (agua),ɪswukʊ (granizo),majpɐt (contar),ɪkutɐ (carnivo),sʊjikʊ (alto_terra),pʊkwisʊn (granizo)
230,,kɐɾʊtatʊ (tronco),ɪpwunɐw (dez),ɐjiwɐ (mudar_cabeca),sʊjujɪ (cordilheira),ʊnɐwipɐ (dez),ɐtɪpuɺɐ (criatura-mitologia),pʊkwitɪ (magma),mapɐ (criar)
231,,ɐkumɐ (fonte),ʊɾɐkiʦɐ (cria),pʊkwitɪ (magma),mabɐ (criar),pʊkwisʊn (granizo),kɐpjakʊ (azul),ɐkupɐt (afluente),ɐkwiwɐ (mar_rio)
232,,ʊmjiwʊ (braco),kɐɾʊjɪsujɪ (cordilheira),ɐkumɐ (riacho),pʊkʊwijɐ (tipo-minerio),ʊmsuʝɪ (membro_alto),kɐlujɪ (cordilheira),petɐ (carnivo),patpɐt (fracao)

In [13]:
ramo_a.ver_gramatica('todos')

==================== Língua original ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ap
||            instrumental  :::  ta
||            genitivo  :::  mij
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾɪ
||            nos_inclusivo  :::  aɾna
||            nos_exclusivo  :::  aɾuɾɪ
||
==================== ikʊ tuwɪ ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ab
||            instrumental  :::  ta
||            genitivo  :::  mij
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾ
||            nos_inclusivo  :::  aɾnɐ
||            nos_exclusivo  :::  ɐɾuɾɪ
||
==================== ikʊ tap ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  a
||            instrumental  :::  ta
||            genitivo  :::  mij
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾɪ
||            nos_inclusivo  :::  aɾnɐ
||            nos_exclusivo  :::  ɐɾuɾɪ
||
==================== ikʊ ja ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ap
||            instrumental  :::  ta
||            genitivo  :::  mij
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾɪ
||            nos_inclusivo  :::  aɾnɐ
||            nos_exclusivo  :::  ɐɾuɾɪ
||
==================== ikʊ imɐw ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ap
||            instrumental  :::  ta
||            genitivo  :::  mji
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾɪ
||            nos_inclusivo  :::  aɾnɐ
||            nos_exclusivo  :::  ɐɾuɾɪ
||
==================== ikʊ uɾjʊ ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ap
||            instrumental  :::  ta
||            genitivo  :::  mji
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾɪ
||            nos_inclusivo  :::  aɾnɐ
||            nos_exclusivo  :::  ɐɾuɾɪ
||
==================== ikʊ utɐm ====================
:::::::::: afixos
||            cargo  :::  atɪb
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ab
||            instrumental  :::  ta
||            genitivo  :::  mij
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾɪ
||            nos_inclusivo  :::  aɾnɐ
||            nos_exclusivo  :::  aɾʊɾ
||
==================== ikʊ an ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ap
||            instrumental  :::  ta
||            genitivo  :::  mji
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾɪ
||            nos_inclusivo  :::  aɾnɐ
||            nos_exclusivo  :::  ɐɾuɾɪ
||
==================== ikʊ nuj ====================
:::::::::: afixos
||            cargo  :::  atɪp
||            locativo  :::  amɐw
||            dativo  :::  mi
||            acusativo  :::  ap
||            instrumental  :::  ta
||            genitivo  :::  mij
||
:::::::::: pronomes
||            eu  :::  aɾ
||            voce  :::  na
||            aquele  :::  uɾ
||            nos_inclusivo  :::  aɾnɐ
||            nos_exclusivo  :::  ɐɾuɾɪ
||